### ISSUE TITLE
how to Install a playground？

### ISSUE THREAD

**Issue by right11112** [jsreport/playground#23]
![image](https://github.com/jsreport/playground/assets/45585783/268226e2-ab4a-42d7-8feb-8fe36d41b3cd)
![image](https://github.com/jsreport/playground/assets/45585783/6d2d6ee9-0f98-46d6-9797-cd7c837d377a)

![image](https://github.com/jsreport/playground/assets/45585783/d59a9bce-fb4f-4b9e-aac1-ebf361ec17d1)
I successfully started jsreport-master, but i failed to start  the  playground-master normally 。
Could you provide a detailed installation tutorial, please?

**Comment by pofider** [comment]
the playground is rather our internal app we host for the public to share workspaces and replicate bugs. We don't plan to take time to make it usable outside of this at this moment.

However, feel free to check the sources and implement some similar jsreport extension that fully matches your needs.
